package com.sar.web.http;

import org.slf4j.LoggerFactory;

import java.util.*;
import java.io.File;
import java.io.IOException;
import java.io.PrintStream;
import java.io.FileInputStream;
import java.text.DateFormat;
import java.text.SimpleDateFormat;

public class Response {
    private static final org.slf4j.Logger logger = LoggerFactory.getLogger(Response.class);
    
    /**
     * Reply code information
     */
    public ReplyCode code;
    
    /**
     * Reply headers data
     */
    public Headers headers; // stores the HTTP headers for the response
    public ArrayList<String> setCookie;   // List to store Set-cookie header fields
    
    /**
     * Reply contents
     * They are stored either in a text buffer or in a file
     */
    public File file;   // file used if text == null, for responses that contain a file  
    public String text; // buffer with reply contents for dynamic API responses or server generated HTML code

    private PrintStream printStream;
    private boolean fullyHandled = false;

    private final String serverName;
    
    /**
     * Creates a new instance of HTTPAnswer
     * @param server_name
     */
    public Response(String server_name) {
        this.code = new ReplyCode();
        this.headers = new Headers();
        this.setCookie = new ArrayList<>();
        this.serverName = server_name;
        this.headers.setHeader("Server", server_name);
    }

    public void setCode(int _code) {
        code.setCode(_code);
    }

    public void setVersion(String v) {
        code.setVersion(v);
    }

    public void setHeader(String name, String value) {
        headers.setHeader(name, value);
    }

    public void setFile(File file) {
        this.file = file;
    }
    
    public void setText(String text) {
        this.text = text;
    }
    
    public void setFullyHandled(boolean fullyHandled) {
        this.fullyHandled = fullyHandled;
    }

    public void setPrintStream(PrintStream ps) {
        this.printStream = ps;
    }

    public void addCookie(String cookie) {
        setCookie.add(cookie);
    }

    /**
     * Sets the headers needed in a reply with a static file content and fills
     * the file property with the File object of the static file to send.
     *
     * Bug fix 5: removed the erroneous second line "this.file = null" which
     * immediately nullified the file reference set on the first line, causing
     * static file responses to always send an empty body.
     *
     * @param file        the file to serve
     * @param contentType the MIME type for the Content-Type header
     */
    public void setFileHeaders(File file, String contentType) {
        this.file = file;
        // Bug was here: this.file = null; <-- removed
        this.headers.setHeader("Content-Type", contentType);
        this.headers.setHeader("Content-Length", String.valueOf(file.length()));
        logger.debug("setFileHeaders: {} ({})", file.getName(), contentType);
    }

    /**
     * Sets the headers needed in a reply with a locally generated HTML string.
     */
    public void setTextHeaders(String text) {
        this.text = text;
        this.file = null;
        logger.debug("Header fields not defined in HTTPAnswer.set_text");
    }

    /**
     * Prepares an HTTP answer with an error code.
     */
    public void setError(int codeNumber, String version) {
        setDate();
        setVersion(version);
        code.setCode(codeNumber);
        setTextHeaders(generateErrorPage(codeNumber));
    }

    private String generateErrorPage(int code) {
        return String.format(
            "<html><head><title>Error %d</title></head>" +
            "<body><h1>Error %d - %s</h1>" +
            "<p>Generated by %s</p></body></html>",
            code, code, ReplyCode.codeText(code), serverName
        );
    }

    void setDate() {
        DateFormat httpformat = new SimpleDateFormat("EE, d MMM yyyy HH:mm:ss zz", Locale.UK);
        httpformat.setTimeZone(TimeZone.getTimeZone("GMT"));
        headers.setHeader("Date", httpformat.format(new Date()));
    }

    public int getCode() {
        return code.getCode();
    }

    public Enumeration<Object> get_Iterator_parameter_names() {
        return headers.getAllHeaderNames();
    }

    public ArrayList<String> getSetCookies() {
        return setCookie;
    }

    public boolean isFullyHandled() {
        return fullyHandled;
    }

    public PrintStream getPrintStream() {
        return printStream;
    }
    
    /**
     * Sends the HTTP reply to the client using the provided PrintStream.
     * @param TextPrinter the output stream connected to the client socket
     * @throws java.io.IOException
     */
    public void send_Answer(PrintStream TextPrinter) throws IOException {
        if (code.getCodeTxt() == null) {
            code.setCode(ReplyCode.BADREQ);
        }
        logger.info("Sending reply: {} {} {}", code.getVersion(), code.getCode(), code.getCodeTxt());
        TextPrinter.print(code.toString() + "\r\n");
        
        // Send all headers
        headers.writeHeaders(TextPrinter);

        // Send Set-Cookie headers (must be done manually since Properties
        // cannot hold duplicate keys)
        for (String cookie : setCookie) {
            TextPrinter.print("Set-Cookie: " + cookie + "\r\n");
        }

        // End of headers
        TextPrinter.print("\r\n");

        // Write body if present
        if (text != null) {
            TextPrinter.print(text);
        } else if (file != null) {
            writeFile(TextPrinter);
        } else if ((code.getCode() != ReplyCode.NOTMODIFIED) && (code.getCode() != ReplyCode.TMPREDIRECT)) {
            logger.error("Internal server error sending answer\n");
        }
    
        TextPrinter.flush();
    }

    private void writeFile(PrintStream TextPrinter) {
        try (FileInputStream fin = new FileInputStream(file)) {
            byte[] data = new byte[fin.available()];
            fin.read(data);
            // IMPORTANT - Please modify this code to send a file chunk-by-chunk
            //             to avoid having CRASHES with BIG FILES
            logger.info("HTTPAnswer may fail for large files - please modify it");
            TextPrinter.write(data);
        } catch (IOException e) {
            System.out.println("I/O error opening FileInputStream " + e);
        }
    }
}
