package com.sar.web.http;

import org.slf4j.LoggerFactory;

import java.util.*;
import java.io.File;
import java.io.IOException;
import java.io.PrintStream;
import java.io.FileInputStream;
import java.text.DateFormat;
import java.text.SimpleDateFormat;

public class Response {
    private static final org.slf4j.Logger logger = LoggerFactory.getLogger(Response.class);
    
    /**
    * Reply code information
    */
    public ReplyCode code;
    
    /**
    * Reply headers data
    */
    public Headers headers; // stores the HTTP headers for the response
    public ArrayList<String> setCookie;   // List to store Set-cookie header fields
    
    /**
    * Reply contents
    * They are stored either in a text buffer or in a file
    */
    public File file;   // file used if text == null, for responses that contain a file  
    public String text; // buffer with reply contents for dynamic API responses or server generated HTML code

    private PrintStream printStream;
    private boolean fullyHandled = false;

    private final String serverName;
    
    /**
    * Creates a new instance of HTTPAnswer
    * @param server_name
    */
    public Response(String server_name) {
        this.code = new ReplyCode(); // code constains an instance of the HTTPReplyCode Class thar contains HTTP code values and an HTTP version field.
        this.headers = new Headers ();  // Headers object to store response HTTP headers  
        this.setCookie = new ArrayList<>(); // Array List of Strings to contain the Strings that make up the several values of the Set_Cookie Header. 
        this.serverName = server_name;
    
        /**
        * define Server header field name
        */
    
        this.headers.setHeader("Server", server_name);
    }

    /* 
    * Method to set the HTTP reply code of the answer
    */
    public void setCode(int _code) {
        code.setCode(_code);
    }

    /* 
    * Method to set the HTTP version of the answer
    */
    public void setVersion(String v) {
        code.setVersion(v);
    }

    /* 
    * Method to set an HTTP header of the answer
    */
    public void setHeader(String name, String value) {
        headers.setHeader(name, value);
    }

    /*
    * Method to set the static file to be sent in the reply
    */
    public void setFile(File file) {
        this.file = file;
    }
    
    /*
    * Method to set the text to be sent in the reply
    */
    public void setText(String text) {
        this.text = text;
    }
    
    /* 
    * Method to mark the response as fully handled
    */
    public void setFullyHandled(boolean fullyHandled) {
        this.fullyHandled = fullyHandled;
    }

    /* 
    * Method to set the PrintStream to be used for sending the response to the client
    */
    public void setPrintStream(PrintStream ps) {
        this.printStream = ps;
    }

    /* 
    * Method to add a cookie value to the list of cookies that are to be sent in Set-Cookie Headers
    */
    public void addCookie(String cookie) {
        setCookie.add(cookie);
    }

    /** Sets the headers needed in a reply with a static file content and fill
    * the file property with the File object of the static file to send
    * @param _f
    * @param mime_enc 
    */
    public void setFileHeaders(File file, String contentType) {
        this.file = file;
        // Bug was here: this.file = null; <-- removed
        this.headers.setHeader("Content-Type", contentType);
        this.headers.setHeader("Content-Length", String.valueOf(file.length()));
        logger.debug("setFileHeaders: {} ({})", file.getName(), contentType);
    }

    /** Sets the headers needed in a reply with a locally generated HTML string
    * (_text object) and fill the text property with the String object 
    * containing the HTML to send
    * @param _text 
    */
    public void setTextHeaders(String text) {
        this.text = text;
        this.file = null;
        logger.debug("Header fields not defined in HTTPAnswer.set_text");
    }

    /** Prepares an HTTP answer with an error code
    * @param _code
    * @param version 
    */
    public void setError(int codeNumber, String version) {
        setDate();
        setVersion(version);
        code.setCode(codeNumber);
        setTextHeaders(generateErrorPage(codeNumber));
    }

    private String generateErrorPage(int code) {
        return String.format(
            "<html><head><title>Error %d</title></head>" +
            "<body><h1>Error %d - %s</h1>" +
            "<p>Generated by %s</p></body></html>",
            code, code, ReplyCode.codeText(code), serverName
        );
    }

    /* Sets the "Date" header field with the local date in HTTP format */
    void setDate() {
        DateFormat httpformat = new SimpleDateFormat("EE, d MMM yyyy HH:mm:ss zz", Locale.UK);
        httpformat.setTimeZone(TimeZone.getTimeZone("GMT"));
        headers.setHeader("Date", httpformat.format(new Date()));
    }

    /**
    * Returns the current value of the answer code
    * @return 
    */
    public int getCode() {
        return code.getCode();
    }

    /**
    * Returns an iterator over all header names
    * @return 
    */
    public Enumeration<Object> get_Iterator_parameter_names() {
        return headers.getAllHeaderNames();
    }

    /**
    * Returns the array list with all cookie Strings to use as values in Set-Cookie Headers
    * @return 
    */
    public ArrayList<String> getSetCookies() {
        return setCookie;
    }

    /* 
    * Method to check if the response is fully handled
    */
    public boolean isFullyHandled() {
        return fullyHandled;
    }

    /* 
    * Method to get the PrintStream to be used for sending the response to the client
    */
    public PrintStream getPrintStream() {
        return printStream;
    }
    
    /**
     * Sends the HTTP reply to the client using the provided PrintStream.
     * @param TextPrinter the output stream connected to the client socket
     * @throws java.io.IOException
     */
    public void send_Answer(PrintStream TextPrinter) throws IOException {
        if (code.getCodeTxt() == null) {
            code.setCode(ReplyCode.BADREQ);
        }
        logger.info("Sending reply: {} {} {}", code.getVersion(), code.getCode(), code.getCodeTxt());
        TextPrinter.print(code.toString() + "\r\n");
        
        // Send all headers
        headers.writeHeaders(TextPrinter);

        // Send Set-Cookie headers (must be done manually since Properties
        // cannot hold duplicate keys)
        for (String cookie : setCookie) {
            TextPrinter.print("Set-Cookie: " + cookie + "\r\n");
        }

        // End of headers
        TextPrinter.print("\r\n");

        // Write body if present
        if (text != null) {
            TextPrinter.print(text);
        } else if (file != null) {
            writeFile(TextPrinter);
        } else if ((code.getCode() != ReplyCode.NOTMODIFIED) && (code.getCode() != ReplyCode.TMPREDIRECT)) {
            logger.error("Internal server error sending answer\n");
        }
    
        TextPrinter.flush();
    }

    private void writeFile(PrintStream TextPrinter) {
        try (FileInputStream fin = new FileInputStream(file)) {
            byte[] data = new byte[fin.available()];
            fin.read(data);
            // IMPORTANT - Please modify this code to send a file chunk-by-chunk
            //             to avoid having CRASHES with BIG FILES
            logger.info("HTTPAnswer may fail for large files - please modify it");
            TextPrinter.write(data);
        } catch (IOException e) {
            System.out.println("I/O error opening FileInputStream " + e);
        }
    }
}
